In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv(r"C:\Users\deves\Downloads\AI_Data.csv")
df.head()

,Unnamed: 0,Name,Roll No,Program,Branch,Semester,Status,Session,AL401- [T],AL402- [T],AL403- [P],AL404- [P],AL405- [P],AL406- [P],Result Description,SGPA,CGPA
0,0,AAKASH PIPALDE,0403AL231001,B.Tech,AL,4,Regular,June-2025,C+,B,A,A,A,A,PASS,7.08,6.71
1,1,AAYUSH PATEL,0403AL231002,B.Tech,AL,4,Regular,June-2025,B,B,B,B,B,B,PASS,6.46,6.38
2,3,ABIR SAXENA,0403AL231004,B.Tech,AL,4,Regular,June-2025,D,C,B,B,B,B,PASS WITH GRACE,5.38,5.50
3,4,AMEY BHOKARIKAR,0403AL231005,B.Tech,AL,4,Regular,June-2025,C,B,A,A,A,A,PASS WITH GRACE,6.71,6.82
4,7,ANTIM JAMLE,0403AL231008,B.Tech,AL,4,Regular,June-2025,F,C+,B+,B+,B+,B+,Fail in AL401,5.33,5.29

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          62 non-null     int64
 1   Name                62 non-null     object
 2   Roll No             62 non-null     object
 3   Program             62 non-null     object
 4   Branch              62 non-null     object
 5   Semester            62 non-null     int64
 6   Status              62 non-null     object
 7   Session             62 non-null     object
 8   AL401- [T]          62 non-null     object
 9   AL402- [T]          62 non-null     object
 10  AL403- [P]          62 non-null     object
 11  AL404- [P]          62 non-null     object
 12  AL405- [P]          62 non-null     object
 13  AL406- [P]          62 non-null     object
 14  Result Description  62 non-null     object
 15  SGPA                62 non-null     float64
 16  CGPA                62 non-null     float64
dtypes: float64(2), int64(2), object(13)
memory usage: 8.4+ KB

In [4]:
df = df.drop(columns=["Unnamed: 0", "Name", "Roll No", "Program", "Branch", "Status", "Session"])
df.head()

,Semester,AL401- [T],AL402- [T],AL403- [P],AL404- [P],AL405- [P],AL406- [P],Result Description,SGPA,CGPA
0,4,C+,B,A,A,A,A,PASS,7.08,6.71
1,4,B,B,B,B,B,B,PASS,6.46,6.38
2,4,D,C,B,B,B,B,PASS WITH GRACE,5.38,5.50
3,4,C,B,A,A,A,A,PASS WITH GRACE,6.71,6.82
4,4,F,C+,B+,B+,B+,B+,Fail in AL401,5.33,5.29

In [5]:
encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = encoder.fit_transform(df[col])

df.head()

,Semester,AL401- [T],AL402- [T],AL403- [P],AL404- [P],AL405- [P],AL406- [P],Result Description,SGPA,CGPA
0,4,3,0,0,0,0,0,3,7.08,6.71
1,4,0,0,2,2,2,2,3,6.46,6.38
2,4,4,2,2,2,2,2,4,5.38,5.50
3,4,2,0,0,0,0,0,4,6.71,6.82
4,4,6,3,3,3,3,3,0,5.33,5.29

In [6]:
X = df.drop(columns=["Result Description"])
y = df["Result Description"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (62, 9)
Target Shape: (62,)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model Training Completed ✅")

Model Training Completed ✅

In [9]:
y_pred = model.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy * 100)

Model Accuracy: 92.3076923076923

In [12]:
print(classification_report(y_test, y_pred, zero_division=1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           3       0.92      1.00      0.96        11
           4       1.00      0.00      0.00         1

    accuracy                           0.92        13
   macro avg       0.97      0.67      0.65        13
weighted avg       0.93      0.92      0.89        13

In [13]:
sample_input = np.array([[
    4,   # Semester
    2,   # AL401
    3,   # AL402
    4,   # AL403
    4,   # AL404
    4,   # AL405
    4,   # AL406
    7.0, # SGPA
    7.2  # CGPA
]])

prediction = model.predict(sample_input)
print("Predicted Result Code:", prediction)

Predicted Result Code: [3]

C:\Users\deves\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(